language: node_js
sudo: required

# safelist
branches:
  only:
  - gmv

cache:
  directories:
    - "node_modules"

before_install:
#  - sudo apt-get update -qq
#  - sudo apt-get install -qq -y ruby
  - gem install --pre sass-css-importer
  - gem install compass
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install -g bower-sync

install:
  - cd $BUILD_PATH
  - echo "WORKSPACE:"
  - pwd
  - ls
  - npm install
  - sudo updatedb; sudo locate grunt
  - /home/travis/.nvm/versions/node/v7.4.0/bin/grunt init --force

script:
  - grunt build

#after_script:
  # brand
  # package
  # qa -> sonar cloud

matrix:
  include:
  - env: BUILD_PATH=./js/components/smartmap-ui
  - env: BUILD_PATH=./
