language: node_js
#sudo: required

# safelist
branches:
  only:
  - gmv

cache:
  directories:
    - '$HOME/.nvm/v0.10.48/lib/node_modules'
    - '$HOME/build/EL-BID/SmartMap/js/components/smartmap-ui/node_modules'
    - '$HOME/build/EL-BID/SmartMap/node_modules'
    - '$HOME/.sonarscanner/cache'

addons:
  sonarcloud:
    organization: "el-bid-github" # the key of the org you chose at step #3
    token:
        secure: "FlQTr+HsrDRtTU8WAwtQ0j/Q61Uooy7Bp7fl2wnh8T50C0xksFOljxrteUfNPRUehd9qwkHI3B0MU5JYTmFrJ14IFTC6d1MRuqF6lGck9wr6By/F0eUMPBiBzYLQqMqLSWpKVkOheF5jgoZhIv3tmj+OmHVRcLFyzALM/5cl8SWABXLFLbf/23bJUdDyzpJIn1Z98K53XP6NylEgDhPPjm40cR37cYsX/NzDkHbHZttqJcsjHuvJzaroT3ZKHktP3ccwBZEhAWoaAMx4au6Yd2N53zumY7PPAzpMrQEnqq81CbYIg4CkeQ7jcA2X2uqTwvYqvOA5KHvpmC1EDvlJMl5MlKKo8kFiPywMNnwTz5gfvJkUAj9nWiv1zVdsumFSAv+JggimiSmD0l6s6wB1Cv39zJOm+lM4lCtdJiWMgpKNxUL2DOxARRYTPcVD/4+bhZne69ZsZeQ6srFuVZ+/75mpeC38jZ9PRuqkJTAMJV4Xun9+8acntVaW2D5ecE/HvYQn0H+qTXOPCgpeWdLWCuGQtMmM9y6i0asUKAsMCpo8FhpoA1kfs7ICZf6TsQXcj7Tclu2FDOTQ4NxTO/t1he3rCUBjKkvkzdg6w7qN+c70t5NXUGbBsjNU5fpE9aAZ+VIMzdXZsyeJcgUG1j74jH+Rg5Cx4Xbfr+K3OAO4mNE="
    branches:
      - gmv

before_install:
#  - sudo apt-get update -qq
#  - sudo apt-get install -qq -y ruby
#  - gem install sass
  - gem install --pre compass
  - gem install --pre sass-css-importer
#  - compass version
#  - sass --compass
#  - npm install -g grunt@~0.4.0
  - npm install -g grunt-cli
#  - which grunt
#  - grunt -V        
#  - npm install -g grunt-init
  - npm install -g bower
  - npm install -g bower-sync

install:
  #- cd $BUILD_PATH
  - BUILD_HOME=`pwd`
  - cd ./js/components/smartmap-ui
#  - echo "WORKSPACE:"
#  - pwd
#  - ls
  - npm install
  - grunt travisinit --force
  - grunt build

  - cd $BUILD_HOME
  - npm install
  - grunt travisinit --force

script:
  - grunt build

after_script:
  # brand
  # package
  # qa
  - sonar-scanner


#matrix:
#  include:
#  - env: BUILD_PATH=./js/components/smartmap-ui
#  - env: BUILD_PATH=./
