language: node_js
sudo: required

# safelist
branches:
  only:
  - gmv

cache:
  directories:
    - "node_modules"

install:
  - cd $BUILD_PATH
  - echo "WORKSPACE:"
  - pwd
  - ls
  - npm install
  - sudo updatedb; sudo locate grunt
  - /home/travis/.npm/grunt init --force

script:
  - grunt build

#after_script:
  # brand
  # package
  # qa -> sonar cloud

matrix:
  include:
  - env: BUILD_PATH=./js/components/smartmap-ui
  - env: BUILD_PATH=./