language: node_js
#sudo: required

# safelist
branches:
  only:
  - gmv

#cache:
#  directories:
#    - "node_modules"

addons:
  sonarcloud:
    organization: "el-bid-github" # the key of the org you chose at step #3
    token:
        secure: "tm7MC+ibZUizBDrDJ53ySxCZBbX6WcLEczh3npM8V6zMKcaVwPMS7mZdpLvl/RdlgVS9G0h/O5+osgKzP3wrfs9Q3Sp9NPz1T93H6YSxEqeY8XXRk6xT4Uup+tMiI5bUThg4S4L9UbMrqEwJ76lH3ksX9SE5vTEsEwv88/+jfMe7L1VnbDMg3rV8i9iN5j08RnNdKWQrXXuuVP1Q4u2X5zXe7xniR6IvKfmVyRUqQ2kuEqLGtO5BA2Kh/OQtqAC2mquC+oxMceGTW7xzp7B+FB7p7wwt8J5sjWwR1E/nI8x3Y4KwFSKXY1t2g+iuXTibZ9TEquLyVYTNrRnNZKtTyjD1FpuAd+nqb1H9QNJLqE9W+bPPT+t2e110+6JloCM8b92j98Oh54JlhoaknF0udQSzNHE8p4tvkaI6upr2ygXdp5iC0IRxK/2IWhNxblvkj4l59Ct3Cuy943oj0UmN0irmNiSEECR63p7aywAh/8V9mYUQmPk9Re/MNEyrmkTrzjkc1V7NHaSEjN7swfg3g0olyb8jmW/Cgy+RpWdDWH8rKqzef61k7TTcIQjXhH86bjZsvwVqrF9yc9VwkOABT0bET0Wny1V2FPKbRrz3nnQMxQ+YIXksoHImJlJOPFxUuQXEGd4r+yj2mdjpQHUf5Rhrfvta9dULRyOfB4J0RuI="
    branches:
      - gmv

before_install:
#  - sudo apt-get update -qq
#  - sudo apt-get install -qq -y ruby
#  - gem install sass
  - gem install --pre compass
  - gem install --pre sass-css-importer
#  - compass version
#  - sass --compass
#  - npm install -g grunt@~0.4.0
  - npm install -g grunt-cli
  - which grunt
  - grunt -V        
#  - npm install -g grunt-init
  - npm install -g bower
  - npm install -g bower-sync

install:
  #- cd $BUILD_PATH
  - BUILD_HOME=`pwd`
  - cd ./js/components/smartmap-ui
#  - echo "WORKSPACE:"
#  - pwd
#  - ls
  - npm install
#  - sudo updatedb; sudo locate grunt
#  - /home/travis/.nvm/v0.10.48/bin/grunt --version
#  - /home/travis/.nvm/v0.10.48/bin/grunt init --force
  - grunt travisinit --force
  - grunt build

  - cd $BUILD_HOME
  - npm install
  - grunt travisinit --force

script:
#  - /home/travis/.nvm/v0.10.48/bin/grunt  build
  - grunt build

after_script:
  - sonar-scanner

#  - sudo updatedb; locate perfect-scrollbar;
  # brand
  # package
  # qa -> sonar cloud

#matrix:
#  include:
#  - env: BUILD_PATH=./js/components/smartmap-ui
#  - env: BUILD_PATH=./
